// Code generated by protoc-gen-go.
// source: metric.proto
// DO NOT EDIT!

/*
Package metrics is a generated protocol buffer package.

It is generated from these files:
	metric.proto

It has these top-level messages:
	Metric
*/
package metrics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Metric struct {
	Measurement string          `protobuf:"bytes,1,opt,name=measurement" json:"measurement,omitempty"`
	Tags        []*Metric_Tag   `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty"`
	Fields      []*Metric_Field `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty"`
	Timestamp   int64           `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Metric) GetTags() []*Metric_Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Metric) GetFields() []*Metric_Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Metric_Tag struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Metric_Tag) Reset()                    { *m = Metric_Tag{} }
func (m *Metric_Tag) String() string            { return proto.CompactTextString(m) }
func (*Metric_Tag) ProtoMessage()               {}
func (*Metric_Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Metric_Field struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *Metric_Field) Reset()                    { *m = Metric_Field{} }
func (m *Metric_Field) String() string            { return proto.CompactTextString(m) }
func (*Metric_Field) ProtoMessage()               {}
func (*Metric_Field) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func init() {
	proto.RegisterType((*Metric)(nil), "metrics.Metric")
	proto.RegisterType((*Metric_Tag)(nil), "metrics.Metric.Tag")
	proto.RegisterType((*Metric_Field)(nil), "metrics.Metric.Field")
}

func init() { proto.RegisterFile("metric.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4d, 0x2d, 0x29,
	0xca, 0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0xf0, 0x8a, 0x95, 0x1a, 0x98,
	0xb8, 0xd8, 0x7c, 0xc1, 0x6c, 0x21, 0x05, 0x2e, 0xee, 0xdc, 0xd4, 0xc4, 0xe2, 0xd2, 0xa2, 0xd4,
	0xdc, 0xd4, 0xbc, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x64, 0x21, 0x21, 0x75, 0x2e,
	0x96, 0x92, 0xc4, 0xf4, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x61, 0x3d, 0xa8, 0x21,
	0x7a, 0x10, 0x03, 0xf4, 0x42, 0x12, 0xd3, 0x83, 0xc0, 0x0a, 0x84, 0x74, 0xb9, 0xd8, 0xd2, 0x32,
	0x53, 0x73, 0x52, 0x8a, 0x25, 0x98, 0xc1, 0x4a, 0x45, 0xd1, 0x95, 0xba, 0x81, 0x64, 0x83, 0xa0,
	0x8a, 0x84, 0x64, 0xb8, 0x38, 0x4b, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x24, 0x58,
	0x14, 0x18, 0x35, 0x98, 0x83, 0x10, 0x02, 0x52, 0xba, 0x5c, 0xcc, 0x21, 0x89, 0xe9, 0x42, 0x02,
	0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x50, 0x67, 0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39,
	0xa5, 0xa9, 0x12, 0x4c, 0x60, 0x31, 0x08, 0x47, 0x4a, 0x9f, 0x8b, 0x15, 0x6c, 0x3a, 0x21, 0x0d,
	0xcc, 0x50, 0x0d, 0x49, 0x6c, 0xe0, 0x20, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf3, 0xb3,
	0xd7, 0x59, 0x22, 0x01, 0x00, 0x00,
}
